server:
  port: 8082
  servlet:
    context-path: /api
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false
        same-site: lax
        path: "/"

logging:
  level:
    root: INFO
    com.example.daugia: DEBUG
    org:
      springframework:
        security: DEBUG

storage:
  provider: SUPABASE
  max-size-mb: ${MAX_IMAGE_MB:5}
  supabase:
    url: ${SUPABASE_URL}
    service-key: ${SUPABASE_SERVICE_ROLE_KEY}
    bucket-products: ${SUPABASE_BUCKET_PRODUCTS:imgs}
    cdn-base: ${SUPABASE_CDN_BASE:}

spring:
  datasource:
    url: "jdbc:mysql://root:kdvQTnGhYZePXKZBXIYtOxfXrjcNDaxE@maglev.proxy.rlwy.net:27782/railway?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh"
    username: root
    password: kdvQTnGhYZePXKZBXIYtOxfXrjcNDaxE
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000  # 5 phút
      max-lifetime: 1200000  # 20 phút
      connection-timeout: 20000  # 20 giây
  mail:
    host: smtp.gmail.com
    port: 587
    username: daugiastu@gmail.com
    password: xitxyfjucokpenwe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

  jackson:
    time-zone: Asia/Ho_Chi_Minh
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB